// 役職マスターデータ
const JOBS = [
  { id: "ikemen", label: "イケメン", title: "いかれバーテンダー", cap: 140 },
  { id: "okinawa", label: "沖縄出身", title: "比嘉んちゅ", cap: 140 },
  { id: "korean", label: "韓国人", title: "イ", cap: 140 },
  { id: "mob", label: "モブ", title: "代表or副代表", cap: 90 },
  { id: "heian", label: "平安生", title: "龍大生", cap: 100 },
  { id: "busaiku", label: "ブサイク", title: "（役職名募集中）", cap: 110 },
  { id: "bijin", label: "美人", title: "ミス龍大", cap: 70, special: "bijin" }, // 30%の肩代わり対象
  { id: "omoshiro", label: "おもしろキャラ", title: "松竹所属芸人", cap: 130 },
  { id: "ijirare", label: "いじられキャラ", title: "おもちゃ", cap: 120 },
  { id: "p_char", label: "p", title: "P", cap: 80 },
  { id: "zako", label: "雑魚", title: "いくらちゃん", cap: 60 },
  { id: "psychopath", label: "サイコパス", title: "パパ", cap: 150 },
  { id: "shugo", label: "酒豪", title: "飲み会番長", cap: 150 },
  { id: "soccer", label: "サッカーキャラ", title: "超絶イケメン天才カリスマフットボールプレイヤー", cap: 150 }
];

// マス目マスターデータ（全100マス）
const MAP_SQUARES = [
  { id: 0, type: "start", text: "宅飲みスタート！", mode: "all", nextId: [1] },
  
  // 役職獲得マス (1～14)
  { id: 1, type: "jobChallenge", text: "【役職マス】イケメン", jobId: "ikemen", mode: "all", nextId: [2] },
  { id: 2, type: "jobChallenge", text: "【役職マス】沖縄出身", jobId: "okinawa", mode: "all", nextId: [3] },
  { id: 3, type: "jobChallenge", text: "【役職マス】韓国人", jobId: "korean", mode: "all", nextId: [4] },
  { id: 4, type: "jobChallenge", text: "【役職マス】モブ", jobId: "mob", mode: "all", nextId: [5] },
  { id: 5, type: "jobChallenge", text: "【役職マス】平安生", jobId: "heian", mode: "all", nextId: [6] },
  { id: 6, type: "jobChallenge", text: "【役職マス】ブサイク", jobId: "busaiku", mode: "all", nextId: [7] },
  { id: 7, type: "jobChallenge", text: "【役職マス】美人", jobId: "bijin", mode: "all", nextId: [8] },
  { id: 8, type: "jobChallenge", text: "【役職マス】おもしろキャラ", jobId: "omoshiro", mode: "all", nextId: [9] },
  { id: 9, type: "jobChallenge", text: "【役職マス】いじられキャラ", jobId: "ijirare", mode: "all", nextId: [10] },
  { id: 10, type: "jobChallenge", text: "【役職マス】p", jobId: "p_char", mode: "all", nextId: [11] },
  { id: 11, type: "jobChallenge", text: "【役職マス】雑魚", jobId: "zako", mode: "all", nextId: [12] },
  { id: 12, type: "jobChallenge", text: "【役職マス】サイコパス", jobId: "psychopath", mode: "all", nextId: [13] },
  { id: 13, type: "jobChallenge", text: "【役職マス】酒豪", jobId: "shugo", mode: "all", nextId: [14] },
  { id: 14, type: "jobChallenge", text: "【役職マス】サッカーキャラ", jobId: "soccer", mode: "all", nextId: [15] },

  // イベントマス (15～99)
  { id: 15, type: "force_stop", text: "【強制ストップマス】入学式", location: "家", mode: "all", nextId: [16] },
  { id: 16, type: "location", text: "初めてのお酒はほろ酔いだよね！", drink: 1, degree: 3, location: "宅飲み", mode: "all", nextId: [17] },
  { id: 17, type: "normal", text: "ビール苦い！嫌い！", drink: 1, degree: 5, location: "家", mode: "all", nextId: [18] },
  { id: 18, type: "location", text: "仲良くなった友達とチャミスルで乾杯！", drink: 1, degree: 13, location: "宅飲み", mode: "all", nextId: [19] },
  { id: 19, type: "location", text: "宅飲み楽しい！酎ハイで乾杯！", drink: 1, degree: 7, location: "宅飲み", mode: "all", nextId: [20] },
  { id: 20, type: "normal", text: "【新歓】UKさんごめんなさい。", drink: 2, degree: 25, location: "家", mode: "all", nextId: [21] },
  { id: 21, type: "location", text: "【新歓】まる。この前お母さんが料理に使ってました。", drink: 2, degree: 13, location: "ももじ", mode: "all", nextId: [22] },
  { id: 22, type: "location", text: "端っこでひそひしてからいた", drink: 1, degree: 5, location: "Qoo", mode: "all", nextId: [23] },
  { id: 23, type: "normal", text: "新歓の記憶が全くない！6マス戻る", move: -6, drink: 0, degree: 0, location: "家", mode: "all", nextId: [24] },
  { id: 24, type: "location", text: "金麦大でかすぎて草！死ぬぅ！", drink: 2, degree: 5, location: "とりき", mode: "all", nextId: [25] },
  { id: 25, type: "location", text: "カラオケ飲みおもろ！", drink: 1, degree: 13, location: "カラオ", mode: "all", nextId: [26] },
  { id: 26, type: "normal", text: "【夏合宿】バス飲みおもろすぎ！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [27] },
  { id: 27, type: "normal", text: "【夏合宿】泊りの飲み会最高やね！", drink: 2, degree: 25, location: "家", mode: "all", nextId: [28] },
  { id: 28, type: "location", text: "まだ夏合宿は終わってねーぜ！", drink: 1, degree: 13, location: "宅飲み", mode: "all", nextId: [29] },
  { id: 29, type: "location", text: "いつまで一緒におんねん", drink: 1, degree: 5, location: "宅飲み", mode: "all", nextId: [30] },
  { id: 30, type: "normal", text: "龍大カップで飲むな！", drink: 1, degree: 40, location: "家", mode: "all", nextId: [31] },
  { id: 31, type: "normal", text: "【秋キャン】パックワイン不味すぎやせんか？？", drink: 1, degree: 16, location: "家", mode: "all", nextId: [32] },
  { id: 32, type: "normal", text: "【秋キャン】昼に黒潮市場でビールま？？", drink: 1, degree: 5, location: "家", mode: "all", nextId: [33] },
  { id: 33, type: "location", text: "練習終わりはやっぱり酔うね！", drink: 1, degree: 13, location: "ぱいぱい", mode: "all", nextId: [34] },
  { id: 34, type: "location", text: "ばおわ合致で", drink: 1, degree: 5, location: "とりき", mode: "all", nextId: [35] },
  { id: 35, type: "force_stop", text: "【強制ストップ】カップル成立！？", eventType: "couple", eventClass: "theme-couple", nextId: [36] },
  { id: 36, type: "normal", text: "", location: "", mode: "all", nextId: [37] },
  { id: 37, type: "normal", text: "", location: "", mode: "all", nextId: [38] },
  { id: 38, type: "location", text: "【龍祭】龍祭乙飲みはももじが良いに決まっている。", drink: 1, degree: 13, location: "ももじ", mode: "all", nextId: [39] },
  { id: 39, type: "normal", text: "", location: "", mode: "all", nextId: [40] },
  { id: 40, type: "normal", text: "", location: "", mode: "all", nextId: [41] },
  { id: 41, type: "normal", text: "リア充は爆発しろ！", drink: 1, degree: 25, location: "家", mode: "all", nextId: [42] },
  { id: 42, type: "normal", text: "【忘年会】", location: "家", mode: "all", nextId: [43] },
  { id: 43, type: "normal", text: "【冬合宿】悲報、さーもんず壊れる", drink: 2, degree: 20, location: "家", mode: "all", nextId: [44] },
  { id: 44, type: "normal", text: "", location: "", mode: "all", nextId: [45] },
  { id: 45, type: "normal", text: "", location: "", mode: "all", nextId: [46] },
  { id: 46, type: "normal", text: "新入生0人の新歓キャンプ", drink: 1, degree: 13, location: "家", mode: "all", nextId: [47] },
  { id: 47, type: "location", text: "【新歓】お花見！いや、もも見やろ！", drink: 2, degree: 5, location: "ももじ", mode: "all", nextId: [48] },
  { id: 48, type: "location", text: "空前のたったブーム襲来", drink: 1, degree: 13, location: "宅飲み", mode: "all", nextId: [49] },
  { id: 49, type: "normal", text: "第一回太江寺、龍の鉤爪！", drink: 1, degree: 16, location: "家", mode: "all", nextId: [50] },
  { id: 50, type: "normal", text: "サントロペにて救急車で運ばれる", drink: 1, degree: 25, location: "家", mode: "all", nextId: [51] },
  { id: 51, type: "normal", text: "【夏合宿】4位", drink: 2, degree: 25, location: "家", mode: "all", nextId: [52] },
  { id: 52, type: "force_stop_rankup", text: "【強制ストップ】ランクアップチャンス！", eventType: "rankup", eventClass: "theme-rankup", nextId: [53] },
  { id: 53, type: "normal", text: "【夏合宿】オレンジジュース取ってごめんなさい。", drink: 1, degree: 13, location: "家", mode: "all", nextId: [54] },
  { id: 54, type: "jobRankup", text: "役職がサッカーキャラなら超絶イケメン天才カリスマフットボールプレイヤーにランクアップ", drink: 0, degree: 0, location: "家", mode: "all", nextId: [55] },
  { id: 55, type: "location", text: "琵琶湖終わりのHAMIKIN", drink: 1, degree: 13, location: "ぱいぱい", mode: "all", nextId: [56] },
  { id: 56, type: "normal", text: "", location: "", mode: "all", nextId: [57] },
  { id: 57, type: "normal", text: "【秋キャン】遅刻してもーた、かたじけない", drink: 1, degree: 25, location: "家", mode: "all", nextId: [58] },
  { id: 58, type: "normal", text: "【秋キャン】中瓶なんて余裕っしょ！", drink: 1, degree: 40, location: "家", mode: "all", nextId: [59] },
  { id: 59, type: "normal", text: "", location: "", mode: "all", nextId: [60] },
  { id: 60, type: "normal", text: "", location: "", mode: "all", nextId: [61] },
  { id: 61, type: "normal", text: "", location: "", mode: "all", nextId: [62] },
  { id: 62, type: "normal", text: "【龍祭】バケツタピオカでぼろ儲け", drink: 1, degree: 0, location: "家", mode: "all", nextId: [63] },
  { id: 63, type: "normal", text: "", location: "", mode: "all", nextId: [64] },
  { id: 64, type: "force_stop_rankup", text: "【強制ストップ】ランクアップチャンス！", eventType: "rankup", eventClass: "theme-rankup", nextId: [65] },
  { id: 65, type: "normal", text: "第二回太江寺", drink: 1, degree: 16, location: "家", mode: "all", nextId: [66] },
  { id: 66, type: "normal", text: "リア充は爆発しろ！", drink: 1, degree: 25, location: "家", mode: "all", nextId: [67] },
  { id: 67, type: "normal", text: "【忘年会】", location: "家", mode: "all", nextId: [68] },
  { id: 68, type: "normal", text: "【成人式】さーもんずの飲み会の方が100倍おもろいわ！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [69] },
  { id: 69, type: "normal", text: "【冬合宿】お酒が足りません！", drink: 1, degree: 25, location: "家", mode: "all", nextId: [70] },
  { id: 70, type: "normal", text: "", location: "", mode: "all", nextId: [71] },
  { id: 71, type: "normal", text: "", location: "", mode: "all", nextId: [72] },
  { id: 72, type: "normal", text: "", location: "", mode: "all", nextId: [73] },
  { id: 73, type: "normal", text: "【新歓】川の中で飲む酒きもちぃ！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [74] },
  { id: 74, type: "normal", text: "", location: "", mode: "all", nextId: [75] },
  { id: 75, type: "normal", text: "ビアガ終わりにバス停で乾杯！", drink: 1, degree: 5, location: "家", mode: "all", nextId: [76] },
  { id: 76, type: "normal", text: "", location: "", mode: "all", nextId: [77] },
  { id: 77, type: "normal", text: "【夏合宿】後輩にいじめられる", drink: 2, degree: 13, location: "家", mode: "all", nextId: [78] },
  { id: 78, type: "force_stop", text: "【強制ストップマス】引退", location: "家", mode: "all", nextId: [79] },
  { id: 79, type: "normal", text: "【夏合宿】これにて中瓶とはおさらばじゃい！", drink: 1, degree: 40, location: "家", mode: "all", nextId: [80] },
  { id: 80, type: "normal", text: "", location: "", mode: "all", nextId: [81] },
  { id: 81, type: "normal", text: "", location: "", mode: "all", nextId: [82] },
  { id: 82, type: "normal", text: "", location: "", mode: "all", nextId: [83] },
  { id: 83, type: "normal", text: "【秋キャン】引退後の秋キャンがいっちゃん楽しいんやから", drink: 1, degree: 13, location: "家", mode: "all", nextId: [84] },
  { id: 84, type: "normal", text: "【秋キャン】ジョーズに飲めましたww", drink: 1, degree: 25, location: "家", mode: "all", nextId: [85] },
  { id: 85, type: "normal", text: "", location: "", mode: "all", nextId: [86] },
  { id: 86, type: "normal", text: "", location: "", mode: "all", nextId: [87] },
  { id: 87, type: "normal", text: "", location: "", mode: "all", nextId: [88] },
  { id: 88, type: "normal", text: "【龍祭】ガイモン参上！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [89] },
  { id: 89, type: "normal", text: "", location: "", mode: "all", nextId: [90] },
  { id: 90, type: "normal", text: "リア充は爆発しろ！", drink: 1, degree: 25, location: "家", mode: "all", nextId: [91] },
  { id: 91, type: "normal", text: "【忘年会】まんぱんまんぱんゲーム！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [92] },
  { id: 92, type: "heal", text: "【冬合宿】ゲレンデのカレーが美味しすぎるのだが", drink: 0, degree: -100, location: "家", mode: "all", nextId: [93] },
  { id: 93, type: "normal", text: "", location: "", mode: "all", nextId: [94] },
  { id: 94, type: "location", text: "【追いコン】みんな今までありがとう！全員で乾杯！", drink: 1, degree: 25, location: "Qoo", mode: "all", nextId: [95] },
  { id: 95, type: "normal", text: "", location: "", mode: "all", nextId: [96] },
  { id: 96, type: "normal", text: "単位が足りない！？そんなの関係ねぇ！", drink: 1, degree: 40, location: "家", mode: "all", nextId: [97] },
  { id: 97, type: "normal", text: "", mode: "all", nextId: [98] },
  { id: 98, type: "force_stop", text: "【留年】もう一回遊べるドン。3マス戻る", location: "家", move: -3, mode: "all", nextId: [99] },
  { id: 99, type: "goal", text: "【ゴール】", isGoal: true, mode: "all", nextId: [] }
];

const MAP_SQUARES = [
  { id: 0, type: "start", text: "宅飲みスタート！", mode: "all", nextId: [1,8] },

  // お前は持っているのか？ルート
  { id: 1, type: "jobChallenge", text: "【役職マス】イケメン", jobId: "ikemen", mode: "all", nextId: [2] },
  { id: 2, type: "jobChallenge", text: "【役職マス】美人", jobId: "bijin", mode: "all", nextId: [3] },
  { id: 3, type: "jobChallenge", text: "【役職マス】サッカーキャラ", jobId: "soccer", mode: "all", nextId: [4] },
  { id: 4, type: "jobChallenge", text: "【役職マス】モブ", jobId: "mob", mode: "all", nextId: [5] },
  { id: 5, type: "jobChallenge", text: "【役職マス】イケメン", jobId: "ikemen", mode: "all", nextId: [6] },
  { id: 6, type: "jobChallenge", text: "【役職マス】ブサイク", jobId: "busaiku", mode: "all", nextId: [7] },
  { id: 7, type: "jobChallenge", text: "【役職マス】サッカーキャラ", jobId: "soccer", mode: "all", nextId: [18] },

  // 来るもの拒まずルート
  { id: 8, type: "jobChallenge", text: "【役職マス】沖縄出身", jobId: "okinawa", mode: "all", nextId: [9] },
  { id: 9, type: "jobChallenge", text: "【役職マス】韓国人", jobId: "korean", mode: "all", nextId: [10] },
  { id: 10, type: "jobChallenge", text: "【役職マス】平安生", jobId: "heian", mode: "all", nextId: [11] },
  { id: 11, type: "jobChallenge", text: "【役職マス】美人", jobId: "bijin", mode: "all", nextId: [12] },
  { id: 12, type: "jobChallenge", text: "【役職マス】おもしろキャラ", jobId: "omoshiro", mode: "all", nextId: [13] },
  { id: 13, type: "jobChallenge", text: "【役職マス】いじられキャラ", jobId: "ijirare", mode: "all", nextId: [14] },
  { id: 14, type: "jobChallenge", text: "【役職マス】p", jobId: "p_char", mode: "all", nextId: [15] },
  { id: 15, type: "jobChallenge", text: "【役職マス】雑魚", jobId: "zako", mode: "all", nextId: [16] },
  { id: 16, type: "jobChallenge", text: "【役職マス】サイコパス", jobId: "psychopath", mode: "all", nextId: [17] },
  { id: 17, type: "jobChallenge", text: "【役職マス】酒豪", jobId: "shugo", mode: "all", nextId: [18] },

  { id: 18, type: "force_stop", text: "【強制ストップマス】入学式", location: "家", mode: "all", nextId: [19] },
  { id: 19, type: "normal", text: "【新歓】UKさんごめんなさい。", drink: 2, degree: 25, location: "家", mode: "all", nextId: [20] },
  { id: 20, type: "location", text: "【新歓】まる。この前お母さんが料理に使ってました。", drink: 2, degree: 13, location: "ももじ", mode: "all", nextId: [21] },
  { id: 21, type: "normal", text: "【夏合宿】バス飲みおもろすぎ！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [22] },
  { id: 22, type: "normal", text: "【夏合宿】泊りの飲み会最高やね！", drink: 2, degree: 25, location: "家", mode: "all", nextId: [23] },
  { id: 23, type: "location", text: "いつまで一緒におんねん", drink: 1, degree: 5, location: "宅飲み", mode: "all", nextId: [24] },
  { id: 24, type: "normal", text: "龍大カップで飲むな！", drink: 1, degree: 40, location: "家", mode: "all", nextId: [25] },
  { id: 25, type: "normal", text: "【秋キャン】パックワイン不味すぎやせんか？？", drink: 1, degree: 16, location: "家", mode: "all", nextId: [26] },
  { id: 26, type: "normal", text: "【秋キャン】昼に黒潮市場でビールま？？", drink: 1, degree: 5, location: "家", mode: "all", nextId: [27] },
  { id: 27, type: "location", text: "【龍祭】龍祭乙飲みはももじが良いに決まっている。", drink: 1, degree: 13, location: "ももじ", mode: "all", nextId: [28] },
  { id: 28, type: "normal", text: "リア充は爆発しろ！", drink: 1, degree: 25, location: "家", mode: "all", nextId: [29] },
  { id: 29, type: "normal", text: "【忘年会】忘れる記憶あんま無くて草", location: "家", mode: "all", nextId: [30] },
  
  { id: 30, type: "force_stop", text: "【強制ストップ】生命保険購入", eventType: "couple", eventClass: "theme-couple", nextId: [31] },
  { id: 31, type: "location", text: "金麦大でかすぎて草！死ぬぅ！", drink: 2, degree: 5, location: "とりき", mode: "all", nextId: [32] },
  { id: 32, type: "normal", text: "【冬合宿】悲報、さーもんず壊れる", drink: 2, degree: 20, location: "家", mode: "all", nextId: [33] },
  { id: 33, type: "normal", text: "新入生0人の新歓キャンプ", drink: 1, degree: 13, location: "家", mode: "all", nextId: [34] },
  { id: 34, type: "location", text: "【新歓】お花見！いや、もも見やろ！", drink: 2, degree: 5, location: "ももじ", mode: "all", nextId: [35] },
  { id: 35, type: "normal", text: "", location: "", mode: "all", nextId: [36] },
  { id: 36, type: "normal", text: "", location: "", mode: "all", nextId: [37] },
  { id: 37, type: "location", text: "空前のたったブーム襲来", drink: 1, degree: 13, location: "宅飲み", mode: "all", nextId: [38] },
  { id: 38, type: "normal", text: "第一回太江寺、龍の鉤爪！", drink: 1, degree: 16, location: "家", mode: "all", nextId: [39] },
  { id: 39, type: "normal", text: "おかみさんに障子を破ったことがばれる。10,000円罰金", location: "家", mode: "all", nextId: [40] },
  { id: 40, type: "normal", text: "サントロペにて救急車で運ばれる", drink: 1, degree: 25, location: "家", mode: "all", nextId: [41] },
  
  { id: 41, type: "force_stop", text: "【強制ストップ】カップル成立！？", eventType: "couple", eventClass: "theme-couple", nextId: [42] },
  { id: 42, type: "location", text: "ばおわ合致で", drink: 1, degree: 5, location: "とりき", mode: "all", nextId: [43] },
  { id: 43, type: "normal", text: "", location: "", mode: "all", nextId: [44] },
  { id: 44, type: "normal", text: "", location: "", mode: "all", nextId: [45] },
  { id: 45, type: "normal", text: "", location: "", mode: "all", nextId: [46] },
  { id: 46, type: "normal", text: "", location: "", mode: "all", nextId: [47] },
  { id: 47, type: "normal", text: "", location: "", mode: "all", nextId: [48] },
  { id: 48, type: "normal", text: "【夏合宿】4位", drink: 2, degree: 25, location: "家", mode: "all", nextId: [49] },
  
  // 激シャバルート
  { id: 49, type: "force_stop_rankup", text: "【強制ストップ】ランクアップチャンス！", eventType: "rankup", eventClass: "theme-rankup", nextId: [50, 59] },
  { id: 50, type: "normal", text: "【夏合宿】オレンジジュース取ってごめんなさい。", drink: 1, degree: 13, location: "家", mode: "all", nextId: [51] },
  { id: 51, type: "normal", text: "カシオレで", location: "家", mode: "all", nextId: [52] },
  { id: 52, type: "normal", text: "恋人とデートに行く", location: "家", mode: "all", nextId: [53] },
  { id: 53, type: "normal", text: "", location: "家", mode: "all", nextId: [54] },
  { id: 54, type: "normal", text: "", location: "家", mode: "all", nextId: [55] },
  { id: 55, type: "normal", text: "いちご狩り行こうぜ！", location: "家", mode: "all", nextId: [56] },
  { id: 56, type: "normal", text: "", location: "家", mode: "all", nextId: [57] },
  { id: 57, type: "normal", text: "", location: "家", mode: "all", nextId: [58] },
  { id: 58, type: "normal", text: "P〇パリピポプチョヘンザ", location: "家", mode: "all", nextId: [80] },

  // 激おもろ一生の思い出ルート
  { id: 59, type: "normal", text: "【夏合宿】オレンジジュース取ってごめんなさい。", drink: 1, degree: 13, location: "家", mode: "all", nextId: [60] },
  { id: 60, type: "location", text: "琵琶湖終わりのHAMIKIN", drink: 1, degree: 13, location: "ぱいぱい", mode: "all", nextId: [61] },
  { id: 61, type: "normal", text: "", location: "家", mode: "all", nextId: [62] },
  { id: 62, type: "normal", text: "", location: "家", mode: "all", nextId: [63] },
  { id: 63, type: "normal", text: "", location: "", mode: "all", nextId: [64] },
  { id: 64, type: "normal", text: "【秋キャン】遅刻してもーた、かたじけない", drink: 1, degree: 25, location: "家", mode: "all", nextId: [65] },
  { id: 65, type: "normal", text: "【秋キャン】中瓶なんて余裕っしょ！", drink: 1, degree: 40, location: "家", mode: "all", nextId: [66] },
  { id: 66, type: "normal", text: "", location: "", mode: "all", nextId: [67] },
  { id: 67, type: "normal", text: "【龍祭】バケツタピオカでぼろ儲け", drink: 1, degree: 0, location: "家", mode: "all", nextId: [68] },
  { id: 68, type: "normal", text: "", location: "", mode: "all", nextId: [69] },
  { id: 69, type: "normal", text: "第二回太江寺", drink: 1, degree: 16, location: "家", mode: "all", nextId: [70] },
  { id: 70, type: "normal", text: "リア充は爆発しろ！", drink: 1, degree: 25, location: "家", mode: "all", nextId: [71] },
  { id: 71, type: "normal", text: "【忘年会】", location: "家", mode: "all", nextId: [72] },
  { id: 72, type: "normal", text: "【成人式】さーもんずの飲み会の方が100倍おもろいわ！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [73] },
  { id: 73, type: "normal", text: "", location: "", mode: "all", nextId: [74] },
  { id: 74, type: "normal", text: "【冬合宿】お酒が足りません！", drink: 1, degree: 25, location: "家", mode: "all", nextId: [75] },
  { id: 75, type: "normal", text: "", location: "", mode: "all", nextId: [76] },
  { id: 76, type: "normal", text: "【新歓】川の中で飲む酒きもちぃ！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [77] },
  { id: 77, type: "normal", text: "", location: "", mode: "all", nextId: [78] },
  { id: 78, type: "normal", text: "", location: "", mode: "all", nextId: [79] },
  { id: 79, type: "normal", text: "【夏合宿】後輩にいじめられる", drink: 2, degree: 13, location: "家", mode: "all", nextId: [80] },

  { id: 80, type: "force_stop", text: "【強制ストップマス】引退（ギャンブル）", location: "家", mode: "all", nextId: [81] },
  { id: 81, type: "normal", text: "【夏合宿】これにて中瓶とはおさらばじゃい！", drink: 1, degree: 40, location: "家", mode: "all", nextId: [82] },
  { id: 82, type: "normal", text: "【秋キャン】引退後の秋キャンがいっちゃん楽しいんやから", drink: 1, degree: 13, location: "家", mode: "all", nextId: [83] },
  { id: 83, type: "normal", text: "【秋キャン】HOT LIMIT", drink: 1, degree: 25, location: "家", mode: "all", nextId: [84] },
  { id: 84, type: "normal", text: "【龍祭】ガイモン参上！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [85] },
  { id: 85, type: "normal", text: "【忘年会】まんぱんまんぱんゲーム！", drink: 1, degree: 13, location: "家", mode: "all", nextId: [86] },
  { id: 86, type: "heal", text: "【冬合宿】ゲレンデのカレーが美味しすぎるのだが", drink: 0, degree: -100, location: "家", mode: "all", nextId: [87] },
  { id: 87, type: "location", text: "【追いコン】みんな今までありがとう！全員で乾杯！", drink: 1, degree: 25, location: "Qoo", mode: "all", nextId: [88] },
  { id: 88, type: "normal", text: "単位が足りない！？そんなの関係ねぇ！", drink: 1, degree: 40, location: "家", mode: "all", nextId: [89] },
  
  // ルーレットで指定の出目を出せたらゴール、出せなかったら隠し留年ルートへ進む
  { id: 89, type: "force_stop", text: "【卒業!?留年!?】ドキドキ！運命のルーレット！", location: "家", move: -3, mode: "all", nextId: [90, 99] },
  
  // 留年ルート
  { id: 90, type: "repeat", text: "【留年】", mode: "all", nextId: [91] },
  { id: 91, type: "repeat", text: "【留年】", mode: "all", nextId: [92] },
  { id: 92, type: "repeat", text: "【留年】", mode: "all", nextId: [93] },
  { id: 93, type: "repeat", text: "【留年】", mode: "all", nextId: [94] },
  { id: 94, type: "repeat", text: "【留年】", mode: "all", nextId: [95] },
  { id: 95, type: "repeat", text: "【留年】", mode: "all", nextId: [96] },
  { id: 96, type: "repeat", text: "【留年】", mode: "all", nextId: [97] },
  { id: 97, type: "repeat", text: "【留年】", mode: "all", nextId: [98] },
  { id: 98, type: "repeat", text: "【留年】", mode: "all", nextId: [99] },
  
  // ゴール
  { id: 99, type: "goal", text: "【ゴール】", isGoal: true, mode: "all", nextId: [] },
];


// 🎯 プレイヤーオブジェクトの雛形（唯一の定義元）
function createPlayer(id, name) {
  return {
    id: id || "p_" + Date.now() + "_" + Math.floor(Math.random() * 1000),
    name: name || "プレイヤー",
    jobId: "mob",
    job: "モブ",
    baseCap: 80,
    bonusCap: 0,
    currentHp: 80,
    drinkCount: 0,
    happiness: 100, // 👈 幸福度の初期値をここで一元管理
    position: 0,
    location: "スタート前",
    isLover: false,
    skipTurn: false,
    hasJob: false
  };
}

// ─── サーバー（Node.js）環境とブラウザ（window）環境へのエクスポート ───
if (typeof module !== "undefined" && module.exports) {
  module.exports = { JOBS, MAP_SQUARES, createPlayer };
} else {
  window.JOBS = JOBS;
  window.MAP_SQUARES = MAP_SQUARES;
  window.createPlayer = createPlayer;
}
